### PR TITLE
fixed WeiDU 'relative command execution' problem

### PR DESCRIPTION
**Pull request by ALIENQuake**

### CODE REVIEW

**Comment by GwendolyneFreddy** [comment]
What was the problem?

**Comment by ALIENQuake** [comment]
The detailed explanation would take a whole day to discuss, the tl;dr version would be "don't create a folder which has the same name as top-level mod folder inside the mod folder itself". It's an accept & forgot PR, I just wanted to let you know so you would be aware of the folder rename for you local copy when you will improve this mod later.

**Comment by GwendolyneFreddy** [comment]
When I update mods, I usually reorganize the mod folder structure when needed. But Ruad belongs to a bunch of mods I had to release in a hurry within a few days and I forgot to rename this particular case. And as the mod installed fine...
Does it break anything with PI?

**Comment by ALIENQuake** [comment]
I don't blame you, don't worry. Yes, PI (to be specific, any mod manager) can't display mod components without this change.

**Comment by ALIENQuake** [comment]
@GwendolyneFreddy Is there anything more which I can do to make this happen?

**Comment by ALIENQuake** [comment]
Yep, that's a valid reason for delaying the release. No problem!

**Comment by GwendolyneFreddy** [comment]
Hoping wisp will be reactive...
On another hand, would it be possible that your package mod releases setup-mymod.exe lower cased (instead of Setup-mymod.exe)?

**Comment by ALIENQuake** [comment]
@GwendolyneFreddy It can be changed but what's the point? Care to elaborate at the [right](https://www.gibberlings3.net/forums/topic/31131-infinity-auto-packager-automatically-generate-and-adds-mod-packages-to-release) place?

**Comment by ALIENQuake** [comment]
@GwendolyneFreddy It seems that WeiDU 248 is delayed and recently more people installing this mod. Do you mind me merging this and creating a new release?

**Comment by GwendolyneFreddy** [comment]
v29.3.0 released. At last! :)

**Comment by ALIENQuake** [comment]
@GwendolyneFreddy Thanks!

**Pull request closed without merging**
